### ISSUE TITLE
Environment variables and config file

### ISSUE THREAD

**Issue by adevoss** [SpencerPearson/helipad-for-raspiblitz#14]
On my Debian VM I'm testing the environment variables with no luck so far.
So I can't say if the following is true for sure (on PiOS).

Environment variables needs to be in quotes ("")
The script omits the quotes.

The config file `helipad.conf` needs to be copied to the same directory as the helipad binary file.
(See src/main.rs:33 in the helipad source code)

Once again, still testing myself.
Can you please confirm if I'm correct?

**Comment by adevoss** [comment]
The environment variables I didn't get to work. I didn't see the 'Working directory' option in the unit file.
If the config file is in that directory the values in that file are used.

> The config file `helipad.conf` needs to be copied to the same directory as the helipad binary file.

Not true because of the 'Working directory' option.

**Comment by adevoss** [comment]
'Working directory' option in the service unit file has to be `/home/helipad/helipad`. Otherwise the website won't start.
You had that right. I thought I could move the `helipad.conf` file by changing this setting.

So my conclusion is that the `helipad.conf` file has to be in this directory, can't be moved and has to be backed up manually.
The environment variables I don't understand how they work or should work.
No problem for me I use the config file.

**Comment by SpencerPearson** [comment]
For the Raspiblitz, we now have it as an installable service in the menus directly, so everything is taken care of automagically. This install script can be found in the Raspiblitz repo here: https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/bonus.helipad.sh

For other operating systems outside of Raspiblitz those issues would fall outside of the scope of this particular repo.
