### ISSUE TITLE
Install fails on Debian

### ISSUE THREAD

**Issue by adevoss** [SpencerPearson/helipad-for-raspiblitz#4]
After pr #3 this error is at the end.
`./bonus.helipad.sh: line 168: /home/admin/config.scripts/internet.hiddenservice.sh: No such file or directory`

The file `internet.hiddenservice.sh` is gone in the `dev` branch (next release 1.7.2 I believe) so that's why.
Don't know how to fix it now (where it has moved to).

**Comment by SpencerPearson** [comment]
Is there a reason you are running the dev branch vs 1.7?

I think you might be able to pull the script in by calling:

`cd config.scripts`

`wget https://raw.githubusercontent.com/rootzoll/raspiblitz/v1.7/home.admin/config.scripts/internet.hiddenservice.sh`

`chmod +x internet.hiddenservice.sh`

I haven't kept up with what changes are taking place within the dev right now so I'm not sure why it doesn't come with the hiddenservice script already loaded. see if that works though!

**Comment by valcanobacon** [comment]
This script is intended to be ran a Raspiblitz box. Generic installation instructions should be hosted elsewhere possibly in the main helipad repo. This thread can be used to figured out a solution to the user's issue but no change is likely to be made to this script. I think instructions without using docker is useful regardless but building off the umbrel docker might also be a good idea.

**Comment by adevoss** [comment]
> Is there a reason you are running the dev branch vs 1.7?

Yes, The `dev` branch is used as what is called the `main` branch in this repo.

When I add `internet.hiddenservice.sh` the Helipad: Boost Tracker page is shown in my browser.
'No data to show yet'. Don't know if that is because there is no data (which is true) or it 'take some time' or simply adding the  `internet.hiddenservice.sh` is not the only thing that has to be changed for the next release of Raspiblitz (v1.7.2)

Why is `internet.hiddenservice.sh` needed for Helipad? To be reachable from the internet? If so, then it should work on my lan.
The data is pulled from the node Helipad is installed on. Am I correct? (when using default setup).

**Comment by adevoss** [comment]
@valcanobacon That's fine. If any changes have to be made I will apply them locally in my setup.
Installation is successful now. Only issue is why `internet.hiddenservice.sh` is removed.
If I'm not mistaken the script has been renamed to `tor.onion-service.sh`.

**Comment by SpencerPearson** [comment]
ah, that makes sense. hiddenservice.sh just creates a TOR hidden service for you to access that port via the TOR network. Myself, I just connect on my LAN.

I'm glad it is working for you! It will say "No data to show yet" indefinitely if you don't have any boosts for it to read. What is your podcast feed?

**Comment by adevoss** [comment]
> Myself, I just connect on my LAN.

Me too. From internet is a bonus.
> What is your podcast feed?

Don't have one. That's why I posted on podcastindex.social.

My question to Dave (and others) is:
Are there any phone apps (most people use only phones) like the new podcast apps without the podcast part?
Just boost (called 'pay' then) to a node id.
I don't know if that is a standard feature of wallets (I expected it to be so).

Don't own a smartphone myself (OTG with an old Nokia).

**Comment by adevoss** [comment]
With #5 I think this issue is solved.
Don't see any boostagrams yet (which is correct).
Have to check my channels. Only one at the moment.
Installation is ok now.

**Comment by SpencerPearson** [comment]
> Are there any phone apps (most people use only phones) like the new podcast apps without the podcast part?
> Just boost (called 'pay' then) to a node id.
> I don't know if that is a standard feature of wallets (I expected it to be so).

Currently the podcasts apps send boosts to a value tag in a podcast feed, so that's the only thing that currently shows up in Helipad. The only app I've used that supports boosting outside of the concept of podcasts is Sphinx, which can be found at https://sphinx.chat 

Helipad is an application that is specifically looking for keysend invoices on the node with TLV records that are associated with the podcasting 2.0 ecosystem

**Comment by adevoss** [comment]
As I understood it Helipad is looking for any keysend invoice. Thanks for your explanation.
Then I'll have to do without the 'pew pew'  sound.

**Comment by SpencerPearson** [comment]
Closing issue; non-Raspiblitz installs fall outside of the scope of this repo
