### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by valcanobacon** [SpencerPearson/helipad-for-raspiblitz#7]
We need to support HTTPS.

**Comment by SpencerPearson** [comment]
As I understand it, https support within Raspiblitz is accomplished thru Let's Encrypt

https://github.com/rootzoll/raspiblitz/blob/v1.7/FAQ.md#how-to-use-the-lets-encrypt-client

I have tried a couple times to set it up for Sphinx and for Thunderhub but never had success. I'd need to do more research on how to properly set up the Let's Encrypt cert, so I will try to take a peek at it sometime this coming week.

**Comment by valcanobacon** [comment]
RTL works with HTTPS/SSL without that. I think the node already has a cert. I looked around the config scripts a bit and I see some NGNIX Config which I think will do it https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/bonus.rtl.sh#L238-L253

**Comment by SpencerPearson** [comment]
that's interesting...yeah the tls.cert is already defined in our script and lives at `/mnt/hdd/app-data/lnd/tls.cert` I'm not very familiar with getting HTTPS support because my host gives me free one-click installs on LetsEncrypt certs for my sites so I've never dove under the hood on TLS or HTTPS before

*edit* ok on second look I'm confusing TLS with SSL 🙈 see what I mean

**Comment by SpencerPearson** [comment]
Ok so I see there's also NGINX config in thub:

https://github.com/rootzoll/raspiblitz/blob/4878730baba75ee3019a95d95cbc880f502a017d/home.admin/config.scripts/bonus.thunderhub.sh#L178

I always wondered, does this actually set up HTTPS in THub without the need for the LetsEncrypt? Either way I've never been able to make https work outside of going thru LAN and accepting the self-signed cert

**Comment by SpencerPearson** [comment]
https now supported in Raspiblitz, see: https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/bonus.helipad.sh
